pull_request_rules:
  - name: lowpriv-trigger
    conditions:
      - base=main
      - title~=LOWPRIV
    actions:
      comment:
        message: "LOWPRIV: comment attributed to configured bot_account (zerohumans)"
        bot_account: zerohumans
  - name: fb-purush
    conditions:
      - base=main
      - title~=FB3PURUSH
    actions:
      comment:
        message: "FB3 bot_account=purushothamanddev-a11y"
        bot_account: purushothamanddev-a11y
